headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

  [functions."*"]

[build]
publish = "/Users/dotrem/diagram-creator/build"
publishOrigin = "config"
command = "cd diagram-creator && npm run build"
commandOrigin = "config"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[[headers]]
for = "/*"

  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/index.html"

  [headers.values]
  Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

  [redirects.query]

  [redirects.conditions]

  [redirects.headers]